---
author: "Luly"
date: "8/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("gmodels")
library("ggplot2")
library("pROC")
library("rpart")
library("rattle")
library("rpart.plot")
library("tinytex")
library("kableExtra")
library("ROSE")
library("tibble")
library("bitops")
library("tidyquant")
library("knitr")
library("plotly")
library("Sim.DiffProc")
library("readxl")
library("usethis")
library("curl")
library("dplyr")
library("tidyr")
library("scales")
library("RColorBrewer")
library("forcats")
library("ggrepel")
library("gridExtra")
```

```{r}
# PARA MAPAS:
# PASO1: Instalar u UPDATEAR los pquetes cli y ellipsis, luego cargarlos:
library("ellipsis")
library("cli")

# PASO2:Instalar el paquete devtools:
library("devtools")
# Warning: si no te corre devtools updatea los paquetes que salgan en el mensaje de error!!

# PASO3: instala el paquete de los mapas directo de github:
install_github("diegovalle/mxmaps")
library("mxmaps")

# PASO4: Ahora, poner en la TERMILAL: brew install pkg-config
# PASO5: Luego poner en la TERMINAL: brew install gdal

# PASO6: corre el siguiente código. Si en la consola te pregnuta algo yes/no/cancel ponle:NO
library("devtools")
install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/")
install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
install.packages("rgdal", configure.args = c("--with-proj-lib=/usr/local/lib/", "--with-proj-include=/usr/local/include/"))
```

#1 Cargar los datos como una serie de tiempo trimestral:
```{r}
data_national1<-ts(data=(read_excel("Data Luly.xlsx", sheet = 2)), start=c(2005,2), end=2021, frequency=4)
data_national1
plot(data_national1)

```

Sólo viendo las gráficas, se ve que conf y m1 son estacionarias.
Delinq y debt tienen al inicio una caída, pero después el comportamiento parece estacionario.
Sólo int y ex muestran tendencia: int decreciente, ex creciente. No son estacionarias.

#2 Hacer estacionarias las variables
```{r}
# TEST DICKEY FULLER

# Null hypothesis = the series is not stationary, it follows a process of random walk

# Opción A: adf.test, "K" es el numero de lags, si k=0 se hace un test dickey fuller normalito
##    Reject if p-value < 0.05: stationary
##    Do NOT reject if p-value > 0.05: not stationary

# Opción B: ur.df
##    Si el valor crítico es MAYOR al test statistic: Sí es estacionaria
##    Si el valor crítico es MENOR al test statistic: Existe raíz unitaria, NO es estacionaria

# Opción C: unitroot_kpss    

library('tseries')
library("quantmod")
library("urca")
library("fpp2")
```

```{r}
# delinq
delinq<-as.vector(subset(data_national1,select= -c(Date,int,conf,m1,debt,ex)))
summary(ur.df(delinq,lags=0))

# int
int<-as.vector(subset(data_national1,select= -c(Date,delinq,conf,m1,debt,ex)))
summary(ur.df(int,lags=0))

# conf
conf<-as.vector(subset(data_national1,select= -c(Date,int,delinq,m1,debt,ex)))
summary(ur.df(conf,lags=0))

# m1
m1<-as.vector(subset(data_national1,select= -c(Date,int,conf,delinq,debt,ex)))
summary(ur.df(m1,lags=0))

# debt
debt<-as.vector(subset(data_national1,select= -c(Date,int,conf,m1,delinq,ex)))
summary(ur.df(debt,lags=0))

# ex
ex<-as.vector(subset(data_national1,select= -c(Date,int,conf,m1,debt,delinq)))
summary(ur.df(ex,lags=0))
```



